version: "3"
services:
  app:
    build: .
    command: python -u itemsAPI/main.py
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mongo:latest
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABSE=inventory
    ports:
      - 27017:27017